# AI Trading Bot Configuration

# API Configuration
api:
  alpaca:
    api_key: "${ALPACA_API_KEY}"
    api_secret: "${ALPACA_API_SECRET}"
    base_url: "https://paper-api.alpaca.markets"  # Use paper trading for safety
    data_url: "https://data.alpaca.markets"
  
  azure_openai:
    endpoint: "${AZURE_OPENAI_ENDPOINT}"
    api_key: "${AZURE_OPENAI_API_KEY}"
    api_version: "${AZURE_OPENAI_API_VERSION}"
    deployment_name: "${AZURE_OPENAI_DEPLOYMENT_NAME}"
  
  newsapi:
    api_key: "${NEWSAPI_API_KEY}"
    base_url: "https://newsapi.org/v2"
  
  alpha_vantage:
    api_key: "${ALPHA_VANTAGE_API_KEY}"
    base_url: "https://www.alphavantage.co/query"

# Trading Configuration
trading:
  max_portfolio_value: 100000  # Maximum portfolio value in USD
  max_position_size_pct: 10    # Maximum position size as percentage of portfolio
  min_position_size: 1000      # Minimum position size in USD
  default_atr_multiplier: 1.0  # Default ATR multiplier for position sizing
  
  # Averaging down configuration
  averaging:
    atr_thresholds: [2.0, 3.0, 4.0]  # ATR thresholds for additional buys
    position_increase_pct: [25, 25, 25]  # Percentage increase at each threshold
  
  # Position monitoring
  monitoring:
    check_interval_minutes: 30      # Check positions every 30 minutes
    enable_automated_management: true  # Enable automated position management
    max_positions_per_ticker: 3     # Maximum number of positions per ticker
    rebalance_threshold: 0.1        # Rebalance when allocation differs by 10%
  
  # Sell conditions
  sell_conditions:
    extended_from_200sma_pct: 15  # Sell half when price is 15% above 200 SMA (more realistic)
    profit_taking_pct: 50          # Take profit at 50% gain (more realistic)
    stop_loss_pct: 25              # Stop loss at 25% loss (protective)

# Technical Analysis Configuration
technical_analysis:
  default_lookback_days: 365
  sma_periods: [21, 50, 200]
  ema_periods: [10, 20, 40]
  atr_period: 5
  atr_factor: 2.5
  
  # NYMO calculation
  nymo:
    lookback_days: 30
    threshold_levels: [-50, -70, -100]

# News Analysis Configuration
news_analysis:
  lookback_days: 1  # Changed from 7 to 1 day (24 hours)
  max_articles_per_ticker: 50  # Increased from 10 to 50 to capture all relevant news
  batch_size: 5  # Number of articles to analyze in a single Azure OpenAI API call
  batch_delay: 2  # Seconds to wait between batches to avoid rate limits
  sentiment_cache_ttl: 24  # Hours to cache sentiment analysis results
  sentiment_weights:
    recent_24h: 1.0  # Full weight for 24-hour news (most important for swing trading)
    recent_3d: 0.3   # Reduced weight for older news
    recent_7d: 0.1   # Minimal weight for week-old news
    older: 0.05      # Very low weight for old news

# Email Configuration
email:
  smtp_server: "${SMTP_SERVER}"
  smtp_port: "${SMTP_PORT}"
  sender_email: "${SENDER_EMAIL}"
  sender_password: "${SENDER_PASSWORD}"
  recipient_emails: "${RECIPIENT_EMAILS}"

# Logging Configuration
logging:
  level: "INFO"
  file_path: "logs/trading_bot.log"
  max_file_size: "10MB"
  backup_count: 5

# Schedule Configuration
schedule:
  market_open_analysis: "09:30"
  intraday_monitoring: "12:00"
  end_of_day_report: "16:00"
  timezone: "America/New_York"
